import os
import re
import json
import sqlite3
import subprocess
from flask import Blueprint, render_template
from app.db import get_db

bp = Blueprint("reports", __name__, url_prefix="/reports")


def load_coverage_data():
    """
    Reads coverage.json generated by pytest-cov.
    Returns (list of module dicts, overall percent) or (None, None)
    if the file does not exist yet.
    """
    base_dir  = os.path.dirname(os.path.abspath(__file__))
    json_path = os.path.normpath(
        os.path.join(base_dir, "..", "..", "coverage.json")
    )

    if not os.path.exists(json_path):
        return None, None

    try:
        with open(json_path) as f:
            data = json.load(f)

        modules       = []
        total_covered = 0
        total_stmts   = 0

        for filepath, info in sorted(data.get("files", {}).items()):
            clean = filepath.replace("\\", "/")
            if "app/" in clean:
                clean = "app/" + clean.split("app/")[-1]

            summary  = info.get("summary", {})
            covered  = summary.get("covered_lines", 0)
            stmts    = summary.get("num_statements", 0)
            pct      = round(summary.get("percent_covered", 0.0), 1)

            total_covered += covered
            total_stmts   += stmts

            modules.append({
                "name":    clean,
                "stmts":   stmts,
                "covered": covered,
                "percent": pct,
            })

        overall = round(
            (total_covered / total_stmts * 100) if total_stmts > 0 else 0.0,
            1
        )
        return modules, overall

    except Exception:
        return None, None


def load_mutation_data():
    """
    Reads directly from .mutmut-cache SQLite database.
    This avoids all emoji/encoding issues on Windows.
    Returns a dict with total, killed, survived, score.
    Returns None if cache does not exist yet.
    """
    base_dir   = os.path.dirname(os.path.abspath(__file__))
    proj_dir   = os.path.normpath(os.path.join(base_dir, "..", ".."))
    cache_path = os.path.join(proj_dir, ".mutmut-cache")

    if not os.path.exists(cache_path):
        return None

    try:
        conn = sqlite3.connect(cache_path)
        conn.row_factory = sqlite3.Row
        cur  = conn.cursor()

        # mutmut stores results in a table called "Mutant"
        # status values: "killed", "survived", "skipped", "timeout"
        cur.execute("""
            SELECT status, COUNT(*) as count
            FROM Mutant
            GROUP BY status
        """)
        rows = cur.fetchall()
        conn.close()

        killed   = 0
        survived = 0
        skipped  = 0
        timeout  = 0

        for row in rows:
            status = (row["status"] or "").lower()
            count  = row["count"]
            if "killed" in status or "ok" in status:
                killed += count
            elif "survived" in status or "bad" in status:
                survived += count
            elif "skipped" in status:
                skipped += count
            elif "timeout" in status:
                timeout += count

        total = killed + survived
        score = round((killed / total * 100) if total > 0 else 0.0, 1)

        # Save a clean report txt
        report_path = os.path.join(proj_dir, "mutation_report.txt")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write("MUTATION TESTING REPORT\n")
            f.write("=" * 40 + "\n")
            f.write(f"Total Mutants : {total}\n")
            f.write(f"Killed        : {killed}\n")
            f.write(f"Survived      : {survived}\n")
            f.write(f"Skipped       : {skipped}\n")
            f.write(f"Mutation Score: {score}%\n")
            f.write("=" * 40 + "\n")

        return {
            "total":    total,
            "killed":   killed,
            "survived": survived,
            "skipped":  skipped,
            "score":    score,
        }

    except Exception as e:
        return {
            "total":    0,
            "killed":   0,
            "survived": 0,
            "skipped":  0,
            "score":    0.0,
        }


@bp.route("/")
def dashboard():
    db = get_db()

    # --- Existing queries (unchanged) ---
    total_bugs = db.execute(
        "SELECT COUNT(*) FROM bugs"
    ).fetchone()[0]

    open_bugs = db.execute(
        "SELECT COUNT(*) FROM bugs WHERE status = 'Open'"
    ).fetchone()[0]

    in_progress_bugs = db.execute(
        "SELECT COUNT(*) FROM bugs WHERE status = 'In Progress'"
    ).fetchone()[0]

    resolved_bugs = db.execute(
        "SELECT COUNT(*) FROM bugs WHERE status = 'Resolved'"
    ).fetchone()[0]

    closed_bugs = db.execute(
        "SELECT COUNT(*) FROM bugs WHERE status = 'Closed'"
    ).fetchone()[0]

    severity_counts = db.execute("""
        SELECT severity, COUNT(*) as count
        FROM bugs
        GROUP BY severity
    """).fetchall()

    total_executions = db.execute(
        "SELECT COUNT(*) FROM test_executions"
    ).fetchone()[0]

    pass_count = db.execute(
        "SELECT COUNT(*) FROM test_executions WHERE result = 'Pass'"
    ).fetchone()[0]

    fail_count = db.execute(
        "SELECT COUNT(*) FROM test_executions WHERE result = 'Fail'"
    ).fetchone()[0]

    total_test_cases = db.execute(
        "SELECT COUNT(*) FROM test_cases"
    ).fetchone()[0]

    # --- Load coverage + mutation data ---
    coverage_modules, coverage_total = load_coverage_data()
    mutation_data                    = load_mutation_data()

    return render_template("reports/dashboard.html",
                           total_bugs=total_bugs,
                           open_bugs=open_bugs,
                           in_progress_bugs=in_progress_bugs,
                           resolved_bugs=resolved_bugs,
                           closed_bugs=closed_bugs,
                           severity_counts=severity_counts,
                           total_executions=total_executions,
                           pass_count=pass_count,
                           fail_count=fail_count,
                           total_test_cases=total_test_cases,
                           coverage_modules=coverage_modules,
                           coverage_total=coverage_total,
                           mutation_data=mutation_data)